In [1]:
!pip install pandas

Requirement already satisfied: pandas in /Users/vanshvats/PYTHON/venv/lib/python3.12/site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in /Users/vanshvats/PYTHON/venv/lib/python3.12/site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/vanshvats/PYTHON/venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/vanshvats/PYTHON/venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
df=pd.read_csv('data.csv')
df.head(5)
df.describe()
df.describe()
df.isnull().any(axis=1)

df.dtypes
df.isnull().sum()
df['Value_filled']=df['Value'].fillna(df['Value'].mean())
df['Value_filled']=df['Value'].fillna(df['Value'.sum()])
df.isnull().any(axis=1)
df.isnull().sum()
df_filled=df.fillna(0)
print(df_filled)
df.isnull().any(axis=1)
df.isnull().sum()
df_filled=df.fillna(0)
print(df_filled)

df['Value_filled']=df['Value'].fillna(df['Value'].mean())

df['Value_fillna']=df['Value'].fillna(df['Value'].mean().astype(int))

AttributeError: 'function' object has no attribute 'sum'

In [14]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [3]:
df=df.rename(columns={'Date':'Sales Data'})
df.head()

   Sales Data Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [31]:
## change datatypes

df['Value_new']=df['Value'].astype(float)
df.head(5)

,Sales Date,Category,Value,Product,Sales,Region,Sales_fillNA,Sales_fillNa,Value_new
0,2023-01-01,A,28.0,Product1,754.0,East,557.130435,557.130435,28.0
1,2023-01-02,B,39.0,Product3,110.0,North,557.130435,557.130435,39.0
2,2023-01-03,C,32.0,Product2,398.0,East,557.130435,557.130435,32.0
3,2023-01-04,B,8.0,Product1,522.0,East,557.130435,557.130435,8.0
4,2023-01-05,B,26.0,Product3,869.0,North,557.130435,557.130435,26.0

In [4]:
df['New Value']=df['Value'].apply(lambda x:x*2)
df

    Sales Data Category  Value   Product  Sales Region  New Value
0   2023-01-01        A   28.0  Product1  754.0   East       56.0
1   2023-01-02        B   39.0  Product3  110.0  North       78.0
2   2023-01-03        C   32.0  Product2  398.0   East       64.0
3   2023-01-04        B    8.0  Product1  522.0   East       16.0
4   2023-01-05        B   26.0  Product3  869.0  North       52.0
5   2023-01-06        B   54.0  Product3  192.0   West      108.0
6   2023-01-07        A   16.0  Product1  936.0   East       32.0
7   2023-01-08        C   89.0  Product1  488.0   West      178.0
8   2023-01-09        C   37.0  Product3  772.0   West       74.0
9   2023-01-10        A   22.0  Product2  834.0   West       44.0
10  2023-01-11        B    7.0  Product1  842.0  North       14.0
11  2023-01-12        B   60.0  Product2    NaN   West      120.0
12  2023-01-13        A   70.0  Product3  628.0  South      140.0
13  2023-01-14        A   69.0  Product1  423.0   East      138.0
14  2023-01-15        A   47.0  Product2  893.0   West       94.0
15  2023-01-16        C    NaN  Product1  895.0  North        NaN
16  2023-01-17        C   93.0  Product2  511.0  South      186.0
17  2023-01-18        C    NaN  Product1  108.0   West        NaN
18  2023-01-19        A   31.0  Product2  578.0   West       62.0
19  2023-01-20        A   59.0  Product1  736.0   East      118.0
20  2023-01-21        C   82.0  Product3  606.0  South      164.0
21  2023-01-22        C   37.0  Product2  992.0  South       74.0
22  2023-01-23        B   62.0  Product3  942.0  North      124.0
23  2023-01-24        C   92.0  Product2  342.0   West      184.0
24  2023-01-25        A   24.0  Product2  458.0   East       48.0
25  2023-01-26        C   95.0  Product1  584.0   West      190.0
26  2023-01-27        C   71.0  Product2  619.0  North      142.0
27  2023-01-28        C   56.0  Product2  224.0  North      112.0
28  2023-01-29        B    NaN  Product3  617.0  North        NaN
29  2023-01-30        C   51.0  Product2  737.0  South      102.0
30  2023-01-31        B   50.0  Product3  735.0   West      100.0
31  2023-02-01        A   17.0  Product2  189.0   West       34.0
32  2023-02-02        B   63.0  Product3  338.0  South      126.0
33  2023-02-03        C   27.0  Product3    NaN   East       54.0
34  2023-02-04        C   70.0  Product3  669.0   West      140.0
35  2023-02-05        B   60.0  Product2    NaN   West      120.0
36  2023-02-06        C   36.0  Product3  177.0   East       72.0
37  2023-02-07        C    2.0  Product1    NaN  North        4.0
38  2023-02-08        C   94.0  Product1  408.0  South      188.0
39  2023-02-09        A   62.0  Product1  155.0   West      124.0
40  2023-02-10        B   15.0  Product1  578.0   East       30.0
41  2023-02-11        C   97.0  Product1  256.0   East      194.0
42  2023-02-12        A   93.0  Product3  164.0   West      186.0
43  2023-02-13        A   43.0  Product3  949.0   East       86.0
44  2023-02-14        A   96.0  Product3  830.0   East      192.0
45  2023-02-15        B   99.0  Product2  599.0   West      198.0
46  2023-02-16        B    6.0  Product1  938.0  South       12.0
47  2023-02-17        B   69.0  Product3  143.0   West      138.0
48  2023-02-18        C   65.0  Product3  182.0  North      130.0
49  2023-02-19        C   11.0  Product3  708.0  North       22.0

In [5]:
grouped_mean=df.groupby('Product')['Value'].mean()
print(grouped_mean)

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64

In [8]:
grouped_agg=df.groupby('Region')['Value'].agg(['mean','sum','count'])
print(grouped_agg)

grouped_agg=df.groupby(['Region'])['Value'].agg(['mean','sum','count'])
print(grouped_agg)

             mean     sum  count
Region
East    42.307692   550.0     13
North   37.666667   339.0      9
South   62.000000   496.0      8
West    61.588235  1047.0     17
             mean     sum  count
Region
East    42.307692   550.0     13
North   37.666667   339.0      9
South   62.000000   496.0      8
West    61.588235  1047.0     17

In [ ]:
df['New Value']=df['Value'].fillna(df['Value'].mean())

In [42]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [43]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

In [47]:
df3=pd.merge(df1,df2,on="Key",how='inner')
df3

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [50]:
df3=pd.merge(df1,df2,on="Key",how='outer')
df3

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [49]:
df3=pd.merge(df1,df2,on="Key",how='left')
df3

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [48]:
df3=pd.merge(df1,df2,on="Key",how='right')
df3

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6

In [ ]:
import pandas as pd